In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('mushrooms.csv')
print(df.shape)

(8124, 23)


In [6]:
df.head(n=10)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   
6     e         b           s         w       t    a               f   
7     e         b           y         w       t    l               f   
8     p         x           y         w       t    p               f   
9     e         b           s         y       t    a               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [8]:
le=LabelEncoder()
#apply transformation eack coloum
ds=df.apply(le.fit_transform)

In [9]:
ds.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [17]:
data=ds.values
print(data.shape)
print(type(data))
print(data[:5,:])
data_y=data[:,0]
data_x=data[:,1:]

(8124, 23)
<class 'numpy.ndarray'>
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


In [18]:
#break data into train and test

In [19]:
x_train,x_test,y_train,y_test=train_test_split(data_x,data_y,test_size=0.2)

In [20]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(6499, 22) (6499,)
(1625, 22) (1625,)


In [21]:
np.unique(y_train)

array([0, 1])

# Bulding Our Classifier!

In [25]:
def prior_prob(y_train,label):
    total_ex=y_train.shape[0]
    class_ex=np.sum(y_train==label)
    return (class_ex)/float(total_ex)

In [26]:
def cond_prob(x_train,y_train,feature_col,feature_val,label):
    x_fealtered=x_train[y_train==label] #its give use the all row witch crosponding colom is lable
    num=np.sum(x_fealtered[:,feature_col]==feature_val) # in all x_fealtered select those whose feature_val matched
    denom=np.sum(y_train==label)
    
    return num/float(denom)


# predicition

In [29]:
def predict(x_train,y_train,xtest):
    """here xtest is single testing point ,n feature"""
    classes=np.unique(y_train)
    n_feature=x_train.shape[1]
    post_probs=[] #List of probiblity for all classes and a given single testing point
    #compute post_probs for every class
    for label in classes:
        #post_c=lickhood*prior
        likehood=1.0
        for f in range(n_feature):
            cond=cond_prob(x_train,y_train,f,xtest[f],label)
            likehood*=cond
        prior=prior_prob(y_train,label)
        post=likehood*prior
        post_probs.append(post)
    pred=np.argmax(post_probs)
    return pred

    
            

In [30]:
output=predict(x_train,y_train,x_test[0])

In [31]:
output

0

In [32]:
y_test[0]

0

In [33]:
output=predict(x_train,y_train,x_test[1])
print(output,y_test[1])

1 1


In [38]:
def score(x_train,y_train,x_test,y_test):
    pred=[]
    for i in range(x_test.shape[0]):
        pred_lable=predict(x_train,y_train,x_test[i])
        pred.append(pred_lable)
    pred=np.array(pred)
    acc=np.sum(pred==y_test)/y_test.shape[0]
    return acc

In [39]:
print(score(x_train,y_train,x_test,y_test))

0.9987692307692307
